- job:
  name: bazel-build-and-test
  run: playbooks/bazel_build_and_test.yaml

- project:
  test:
    jobs:
      - noop
  check:
    jobs:
      - bazel-build-and-test
      - noop
  gate:
    jobs:
      - bazel-build-and-test
      - noop