- hosts: all
  tasks:    
    - name: Run bazel build
      shell: |
        cd /root/src/gerrit/proving-grounds/
        bazel build //...

    - name: Run bazel test
      shell: |
        cd /root/src/gerrit/proving-grounds/
        bazel test --test_output=all --cache_test_results=no //...
        